version: "3"
services:
  frontend:
    image: asajjad2/doctor-appointment-frontend:frontend-8
    ports:
      - "3000:3000"
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    depends_on:
      - doctors
      - appointments

  doctors:
    image: asajjad2/doctor-appointment-doctors-microservice:doctors-6
    ports:
      - "9090:9090"

  appointments:
    image: asajjad2/doctor-appointment-appointments-microservice:appointments-6
    ports:
      - "7070:7070"
