apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appointments
          image: asajjad2/doctor-appointment-appointments-microservice:latest
          ports:
            - containerPort: 7070
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 7070
            initialDelaySeconds: 15
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /ready
              port: 7070
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: NAME
              valueFrom:
                secretKeyRef:
                  name: appointment
                  key: NAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appointment
                  key: PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: appointments
spec:
  type: ClusterIP
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
---
apiVersion: v1
kind: Secret
metadata:
  name: appointment
type: Opaque
data:
  NAME: YXJlZWJzYWpqYWQ=
  PASSWORD: bWFkYWdhc2NhcjIx
