apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
        - name: doctors
          image: asajjad2/doctor-appointment-doctors-microservice:latest
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 2
          volumeMounts:
            - name: config-volume
              mountPath: /user/details.txt
              subPath: details.txt
      volumes:
        - name: config-volume
          configMap:
            name: doctors

---
apiVersion: v1
kind: Service
metadata:
  name: doctors
spec:
  type: ClusterIP
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: doctors
data:
  details.txt: |
    Hey, I am Areeb!
    👀 I'm interested in Product design & development, machine-learning and RTS games!
    📫 Connect with me on linkedIn:: www.linkedin.com/in/areeb-sajjad-985519210
