apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
        - name: doctors
          image: asajjad2/doctor-appointment-doctors-microservice:latest
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: doctors
spec:
  type: ClusterIP
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
