name: Doctors CI/CD

on:
  push:
    paths:
      - "doctors/**"
  pull_request:
    paths:
      - "doctors/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./doctors
          file: ./doctors/Dockerfile
          push: true
          tags: asajjad2/doctor-appointment-doctors-microservice:doctors-${{ github.run_number }}

      - name: Checkout the repo into a different directory
        uses: actions/checkout@v2
        with:
          repository: asajjad2/doctor-appointment-system
          token: ${{ secrets.PAT }}
          path: temp

      - name: Pull latest changes from main
        run: |
          cd temp
          git pull origin main

      - name: Update docker-compose.yml
        run: |
          cd temp
          sed -i 's|asajjad2/doctor-appointment-doctors-microservice:[^ ]*|asajjad2/doctor-appointment-doctors-microservice:doctors-${{ github.run_number }}|' docker-compose.yml  
          git config --global user.name 'asajjad2'
          git config --global user.email 'areebsajjad21@gmail.com'
          git add docker-compose.yml
          git commit -m "Update doctors service to ${{ github.run_number }}"
          git push

      - name: Clean up
        run: rm -rf temp
